### ISSUE TITLE
Working with a new data other than the sample 

### ISSUE THREAD

**Issue by alcnn** [ntthung/shy#1]
The code is working fine with the sample data, i.e., ONI and Angat; however, when I use my own data, I receive an error in Q_reps function about the use of ":=". This happens even i introduced the sample data as it is. 

![capture](https://user-images.githubusercontent.com/37202014/48751362-ea153580-ecbe-11e8-8c72-9bcb5ce185f5.PNG)

**Comment by ntthung** [comment]
Thanks @alcin. Closed by internally convert input data into data.table.
